### ISSUE TITLE
interpolate_line() crashes R

### ISSUE THREAD

**Issue by allopole** [geanders/stormwindmodel#40]
`interpolate_line()` crashes R.  (`interporlate_spline()` works fine.)

`stormwindmodel` Version: 0.1.5.9

platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          1.0                         
year           2021                        
month          05                          
day            18                          
svn rev        80317                       
language       R                           
version.string R version 4.1.0 (2021-05-18)
nickname       Camp Pontanezen

**Comment by allopole** [comment]
Problem appears to be in `src/interpolation.cpp` line 164:
`int i, l;`
Sourcing fails because `l` needs to be initialized. This fixed it for me:
`int i, l = 0;`

**Comment by geanders** [comment]
Thanks very much, @allopole. We're looking into this right now, and thanks so much for the suggested fix.
